"TimeUTC","timestampInMs","requestPath","requestMethod","requestQueryString","responseStatusCode","requestId","requestUserAgent","level","environment","branch","vercelCache","type","function","host","deploymentDomain","deploymentId","durationMs","region","maxMemoryUsed","memorySize","message","projectId"
"2025-03-18 05:49:14",1742276954514,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"nccmh-1742276952962-c7111fb8fd69","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:49:13",1742276953346,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"nccmh-1742276952962-c7111fb8fd69","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1151,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:49:12",1742276952715,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"ppdv5-1742276951159-d155a3e3b327","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:49:11",1742276951534,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"ppdv5-1742276951159-d155a3e3b327","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1163,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:46",1742276926235,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",-1,"wsbnf-1742276925056-65b40a4a3518","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:45",1742276925092,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",500,"wsbnf-1742276925056-65b40a4a3518","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1125,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:42",1742276922975,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",-1,"g2bnp-1742276921804-085ff564f32a","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:41",1742276921841,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",500,"g2bnp-1742276921804-085ff564f32a","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1120,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:40",1742276920916,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"zw4n5-1742276919710-4451d7fb947c","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:40",1742276920715,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",-1,"pqjpv-1742276919519-b6ca5e30646f","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919752,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"zw4n5-1742276919710-4451d7fb947c","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1147,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919555,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.png","GET","",500,"pqjpv-1742276919519-b6ca5e30646f","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1142,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919547,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"dntfv-1742276918353-3b4cb45abba6","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919476,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"bwkkw-1742276918236-5a736422b692","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919139,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"2h9mh-1742276917941-3a3699031b36","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919122,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"gvz89-1742276917954-dc2194583753","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:39",1742276919017,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"k8p4l-1742276917909-84acbe9f51ce","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:38",1742276918389,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"dntfv-1742276918353-3b4cb45abba6","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1142,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:38",1742276918289,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"bwkkw-1742276918236-5a736422b692","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1170,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:38",1742276918238,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"rgh8n-1742276917069-e67c59ca0fbf","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917991,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"gvz89-1742276917954-dc2194583753","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1118,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917977,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"2h9mh-1742276917941-3a3699031b36","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1143,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917947,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"k8p4l-1742276917909-84acbe9f51ce","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1053,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917853,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"6b6fz-1742276916722-59354a1b37c3","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917842,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"j4xpq-1742276916626-ca924ef273da","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917833,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"rtl8w-1742276916627-23e9e0685e61","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:37",1742276917105,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"rgh8n-1742276917069-e67c59ca0fbf","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1116,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916772,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"vk4lz-1742276915581-55257e95719b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916756,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"6b6fz-1742276916722-59354a1b37c3","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1084,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916682,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"j4xpq-1742276916626-ca924ef273da","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1143,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916665,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"rtl8w-1742276916627-23e9e0685e61","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1152,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916606,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"z8p98-1742276915385-5e1bb00a3cbb","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916503,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"7tb8k-1742276915300-8ec7996dcec2","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:36",1742276916151,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"2nzfq-1742276915044-0a3e1a21643c","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:35",1742276915620,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"vk4lz-1742276915581-55257e95719b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1134,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:35",1742276915420,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"z8p98-1742276915385-5e1bb00a3cbb","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1171,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:35",1742276915338,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"7tb8k-1742276915300-8ec7996dcec2","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1147,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:35",1742276915079,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"2nzfq-1742276915044-0a3e1a21643c","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1059,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:34",1742276914993,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"zjqzb-1742276913880-83dd9f44c58d","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:33",1742276913959,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",-1,"wnppn-1742276912593-596d492152f8","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:33",1742276913918,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"zjqzb-1742276913880-83dd9f44c58d","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1060,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:33",1742276913519,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"glqgh-1742276912388-a24fa3b09712","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:33",1742276913257,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"jkdjg-1742276911918-e0cc73c9475c","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:33",1742276913211,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"22n58-1742276912001-156add734022","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912738,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/favicon.ico","GET","",500,"wnppn-1742276912593-596d492152f8","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1205,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912573,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"pqjpv-1742276910022-ae743acff862","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912466,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"tn924-1742276911269-5ef747ef51b9","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912427,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"glqgh-1742276912388-a24fa3b09712","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1075,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912049,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"jkdjg-1742276911918-e0cc73c9475c","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1187,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:32",1742276912046,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"22n58-1742276912001-156add734022","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1146,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:31",1742276911320,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"tn924-1742276908817-6f404be33a16","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:31",1742276911307,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"tn924-1742276911269-5ef747ef51b9","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1142,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:31",1742276911268,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"sr8vf-1742276908745-403ed0d62291","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:30",1742276910906,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"tdx8n-1742276908149-b33dd6648263","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:30",1742276910852,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",-1,"fpf4h-1742276909710-c57c0483d48d","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/wsgi.py"", line 1, in <module>
from app import app
File ""/var/task/app.py"", line 10, in <module>
logging.basicConfig(filename='app.log', level=logging.INFO)
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 2118, in basicConfig
h = FileHandler(filename, mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1231, in __init__
StreamHandler.__init__(self, self._open())
^^^^^^^^^^^^
File ""/var/lang/lib/python3.12/logging/__init__.py"", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/var/task/app.log'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:30",1742276910156,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"pqjpv-1742276910022-ae743acff862","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1161,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:29",1742276909749,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"fpf4h-1742276909710-c57c0483d48d","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1081,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:28",1742276908886,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"sr8vf-1742276908745-403ed0d62291","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1149,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:28",1742276908885,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"tn924-1742276908817-6f404be33a16","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1127,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
"2025-03-18 05:48:28",1742276908449,"com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app/","GET","",500,"tdx8n-1742276908149-b33dd6648263","vercel-screenshot/1.0","error","production","main","MISS","lambda","/wsgi.py","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","com-pro-dmsa-7fg077rck-zyntax118s-projects.vercel.app","dpl_DtC8ThzbmmYy5JzXCj9u5k6wVi8X",1157,"iad1",65,1024,"","prj_J9E0MLN6Pr0dPAsGuuQ8ahZR4A66"
